import pandas as pd

def get_player_dataset() -> pd.DataFrame:
    return pd.read_csv("src/sources/Fifa_23_Players_Data.csv", usecols=[
    "Best Position",
    "Height(in cm)",
    "Pace Total",
    "Shooting Total",
    "Passing Total",
    "Dribbling Total",
    "Defending Total",
    "Physicality Total",
    "Crossing",
    "Finishing",
    "Heading Accuracy",
    "Short Passing",
    "Volleys",
    "Dribbling",
    "Curve",
    "Freekick Accuracy",
    "Long Passing",
    "Ball Control",
    "Acceleration",
    "Sprint Speed",
    "Agility",
    "Reactions",
    "Balance",
    "Shot Power",
    "Jumping",
    "Stamina",
    "Strength",
    "Long Shots",
    "Aggression",
    "Interceptions",
    "Positioning",
    "Vision",
    "Penalties",
    "Composure",
    "Marking",
    "Standing Tackle",
    "Sliding Tackle",
    "Goalkeeper Diving",
    "Goalkeeper Handling",
    "Goalkeeper Kicking",
    "Goalkeeper Positioning",
    "Goalkeeper Reflexes",
])